# Generated by Django 3.1.5 on 2021-01-22 14:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assignments_view_app', '0002_assignment_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='title',
        ),
        migrations.AddField(
            model_name='assignment',
            name='post_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='question_content',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='text',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.CreateModel(
            name='PublicAssignmentComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_time', models.DateTimeField(default=datetime.datetime.now)),
                ('text', models.CharField(default='', max_length=1000)),
                ('corres_post', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='assignments_view_app.assignment')),
                ('poster', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrivateAssignmentSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_time', models.DateTimeField(default=datetime.datetime.now)),
                ('is_edited', models.BooleanField()),
                ('is_late', models.BooleanField()),
                ('is_graded', models.BooleanField()),
                ('grade', models.IntegerField(default=0)),
                ('corres_post', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='assignments_view_app.assignment')),
                ('poster', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrivateAssignmentComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=1000)),
                ('post_time', models.DateTimeField(default=datetime.datetime.now)),
                ('corres_post', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='assignments_view_app.assignment')),
                ('poster', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
