# Generated by Django 3.1.5 on 2021-01-22 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments_view_app', '0003_auto_20210122_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='is_done',
        ),
    ]
